agglayer/agglayer-contracts

- README.md
- deployment/deployment_v2-0/genesis.json
- update `README.md`
- remove unnecessary data
> update readme & remove data

- src/permit-helper.js
import `ethers` from `ethers` directly intead from `hardhat`
> fix import ethers

- deployment/deployment_v2-0/deployPoE_v2-0.js
- deployment/deployment_v2-0/deploy_parameters.json
> update docker contracts

- deployment/2_deployPolygonZKEVMDeployer.js
- deployment/3_deployContracts.js
- deployment/README.md
- deployment/deploy_parameters.json.example
- deployment/helpers/deployment-helpers.js
- hardhat.config.js
- test/contracts/polygonZkEVMTestnetV2.test.js
> update deploy readme

- package-lock.json
- package.json
- update `zkevm-commonjs` to `v2.0.0-fork.5` version
> update package commonjs

- contracts/mainnetUpgraded/PolygonZkEVMUpgraded.sol
> removed warning

- .github/workflows/security-build.yml
- SECURITY.md
- sonar-project.properties
- create security.md
- sonarcloud properties update
- sonarcloud yml added
> Security update

- contracts/v2/PolygonRollupManager.sol
- contracts/v2/PolygonZkEVMGlobalExitRootV2.sol
- test/contractsv2/PolygonGlobalExitRootV2.test.ts
- test/contractsv2/PolygonRollupManager.test.ts
- test/contractsv2/PolygonRollupManagerUpgrade.test.ts
- update event
- Fix Accumulated fees
> update l1 event

- contracts/v2/lib/PolygonRollupBaseFeijoa.sol
- test/contractsv2/PolygonValidiumFeijoa.test.ts
- test/contractsv2/PolygonZkEVMFeijoa.test.ts
- update tx byte constant to be more consistent with the blob tx data
> update tx btye constnat

- contracts/v2/PolygonZkEVMGlobalExitRootV2.sol
- test/contractsv2/PolygonGlobalExitRootV2.test.ts
- test/contractsv2/PolygonValidiumEtrog.test.ts
- test/contractsv2/PolygonZkEVMEtrog.test.ts
- Fixed all tests except rollupmanager tests for banana
- Fix l1InfoRoot when l1InfoIndex is zero
> Fix all tests except rollup manager

- .github/workflows/build-docker.yml
- .github/workflows/build-push-docker.yml
- contracts/v2/PolygonRollupManager.sol
- src/pessimistic-utils.js
- test/contractsv2/PolygonRollupManager-Pessimistic.test.ts
- add `rollupID` as a a public input
- separate gha actions
- `build-docker` --> just checks if the docker image has been created succesfully
- `build-push-docker` --> builds and push docker to docker-hub
> add rollupID as a public input

- docker/scripts/v2/deploy-docker.sh
- docker/scripts/v2/deploy-dockerv2.sh
- hardhat.config.ts
- package.json
- fix `hardhat.config.ts` optimizer `PolygonRollupManagerNotUpgraded`
- fix sudo build dockers
> fix build docker

- tools/addRollupType/addRollupTypeTimelock.ts
- tools/deployClaimCompressor/deployClaimCompressor.ts
- `addRollupType` tool
- remove the need of `polTokenAddress` parameter
- `deployClaimCompressor`
- fix log
> minor fixes on tools

- deployment/v2/3_deployContracts.ts
Cherry pick https://github.com/0xPolygonHermez/zkevm-contracts/commit/fe26605f34e19eaf3f31042903e185360cea5a6d which initialize `polygonZkEVMGlobalExitRoot`
> disable initializer=false

- upgrade/upgradeBanana/upgradeBanana.ts
- fixes missing `deployer` when deploying `PolygonRollupManager`
- adds full decoded data (`timelock data` & `payloads`) to output `json` upgrade
> decode timelock tx in upgrade-banana

- verifyMainnetDeployment/verifyMainnetProofVerifier.md
typo on command  to build fflonk_setup tool generation. With this typo makefile no generates this tool
> fix a typo on documentation

- contracts/v2/sovereignChains/BridgeL2SovereignChain.sol
Add comment to bridge manager recommending set a timelock
> Add comment bridge Manager

- deployment/v2/1_createGenesis.ts
- Update create genesis contract naming
> Update create genesis contract naming

- contracts/lib/TokenWrappedBridge.sol
- contracts/v2/interfaces/IPolygonConsensusBase.sol
- contracts/v2/interfaces/IPolygonRollupManager.sol
- add comment on tokenBridge
- Cleaner interfaces
> comments and interfaces

- deployment/v2/4_createRollup.ts
- deployment/v2/README.md
- docker/README.md
- docker/scripts/v2/deploy_parameters_docker.json
- docker/scripts/v2/tests-docker.sh
- docker/tools-docker-tests.test.ts
- package-lock.json
- package.json
- tools/addRollupType/.gitignore
- tools/addRollupType/addRollupType.ts
- tools/addRollupType/add_rollup_type_output.json
Added tests for tools:
- create rollup
- create rollup type
Improved docs for docker usage
> Create testing for tools

- test/contractsv2/AggLayerGateway.test.ts
- test/contractsv2/AggchainECDSA.test.ts
- Add `AggLayerGateway` unit test
- Add `AggchainECDSA` unit test
> Feature/ongoing v0.3.0 tests unit

- contracts/lib/GlobalExitRootLib.sol
- contracts/v2/PolygonRollupManager.sol
- contracts/v2/lib/DepositContractBase.sol
- contracts/v2/lib/Hashes.sol
- contracts/v2/sovereignChains/GlobalExitRootManagerL2SovereignChain.sol
uses `_efficientKeccak` to save GAS
> use efficient hash

- contracts/v2/previousVersions/PolygonRollupManagerPreviousV1toV2.sol
- test/contractsv2/PolygonRollupManagerUpgrade.test.ts
- complete test full flow for the `PolygonRollupManager.sol` upgrade
- adds previous version
> full flow previous versions

- contracts/v2/periphery/ClaimCompressor.sol
Move claim compressor to pheriphery
> move claim compressor

- tools/deploySovereignTest/deploySovereign.ts
Add some test deploy to check the sovereign contracts inside SP1 proof
> test sovereignAdd some test deploy to check the sovereign contracts inside SP1 proof

- contracts/v2/sovereignChains/BridgeL2SovereignChain.sol
Proposal for global index hash chain: https://github.com/0xPolygonHermez/protocol-team-kanban/issues/488#issuecomment-2690761507
> Feature: global index hashchain

- upgrade/utils.ts
- fixes `decodeScheduleData` utils
> fix utils decodeScheduleData

- contracts/v2/PolygonZkEVMBridgeV2.sol
- add comment on `claimMessage` function
> add comment

- contracts/v2/PolygonZkEVMBridgeV2.sol
- contracts/v2/sovereignChains/BridgeL2SovereignChain.sol
> set versions

- tools/createNewRollup/createNewRollup.ts
Fix createNewRollup tool:
- Update `initialize` function (ambiguous error)
> fix createNewRollup tool initialize pessimistic

- contracts/v2/PolygonZkEVMBridgeV2.sol
- contracts/v2/interfaces/IPolygonZkEVMBridgeV2.sol
- hardhat.config.ts
- Check that global index does not have unused bits to 1
> check global index

- test/contractsv2/BridgeL2SovereignChain.test.ts
- Add test invalid global index: flag mainnet + `2**65 - 2**256`
> add test invalid global index

- .github/workflows/build-docker.yml
- .github/workflows/compile.yml
- .github/workflows/main.yml
- docs/generate_changelog.ts
Adds test for `feature/outposts` branch
Fix linter issues
> trigger tests on feature/outposts branch

- contracts/v2/AggLayerGateway.sol
- contracts/v2/PolygonRollupManager.sol
- contracts/v2/aggchains/AggchainECDSAMultisig.sol
- contracts/v2/aggchains/AggchainFEP.sol
- contracts/v2/interfaces/IAggLayerGateway.sol
- contracts/v2/interfaces/IAggchainBase.sol
- contracts/v2/interfaces/IAggchainSigners.sol
- contracts/v2/interfaces/IPolygonConsensusBase.sol
- contracts/v2/interfaces/IPolygonRollupManager.sol
- contracts/v2/lib/AggchainBase.sol
- contracts/v2/lib/PolygonConsensusBase.sol
- contracts/v2/previousVersions/aggchain/IAggchainBasePrevious.sol
- deployment/v2/create_rollup_parameters.json.example
- docker/scripts/v2/create_rollup_parameters_docker-v0.3.0-ecdsa.json
- docs/contracts/src/contracts/v2/interfaces/IAggchainBase.sol/interface.IAggchainBaseErrors.md
- hardhat.config.ts
- test/contractsv2/AggLayerGateway.test.ts
- test/contractsv2/AggchainECDSAMultisig.test.ts
- test/contractsv2/AggchainFEP.test.ts
- test/contractsv2/AggchainMetadataSimple.test.ts
- test/contractsv2/PolygonRollupManagerAL-ECDSAMultisig.test.ts
- test/contractsv2/PolygonRollupManagerAL-FEP.test.ts
- test/contractsv2/PolygonRollupManagerALUpgrade.test.ts
- test/contractsv2/UpgradeAggchains.test.ts
- test/contractsv2/UpgradeToPP.test.ts
- test/src/aggchain-FEP.test.ts
- tools/aggchainFEPTools/toolsData/getInitializeAggchainBytesV1.ts
- tools/initializeRollup/initializeRollup.ts
Solves all the following comments:
- from: https://github.com/agglayer/agglayer-contracts/pull/504#discussion_r2314161135
- to: https://github.com/agglayer/agglayer-contracts/pull/504#discussion_r2314234731
- internal-audit issue (private link): https://github.com/agglayer/internal-audit/issues/182
Solves internal audit issues(private link):
- https://github.com/agglayer/internal-audit/issues/179
- https://github.com/agglayer/internal-audit/issues/180
- https://github.com/agglayer/internal-audit/issues/181
> internal audit fixes and PR comments

- contracts/v2/lib/AggchainBase.sol
- Internal audit fixes:
- Add a comment regarding `useDefaultSigners` storage slot
- [related internal audit issue](https://github.com/agglayer/internal-audit/issues/187)
- Don't use `isSigner` inside `_addSignerInternal` for consistency
- [related internal audit issue](https://github.com/agglayer/internal-audit/issues/188)
> Internal audit + initializaiton fixes
