agglayer/agglayer-contracts

deployment/deployment_v2-0/deployPoE_v2-0.js, deployment/deployment_v2-0/deploy_parameters.json, docker/scripts/deploy-docker.sh, test/contracts/proofOfEfficiency.test.js
A new feature implemented in the node requires the Sequencer URL to match the containers we are running
=> fix sequencer URL

docker/scripts/deploy-dockerv2.sh, package.json
The current docker deployment script will not work with docker compose v2 installed and throws an error of unknown command "docker-compose"
Updated the script to docker compose v2
Issue: https://github.com/0xPolygonHermez/zkevm-contracts/issues/128
=> updated deploy-docker.sh to docker compose v2

deployment/v2/4_createRollup.ts
The PR fixes create rollup deployment script. There were missing `Address` suffixes on a couple of places for `polygonRollupManager` SC address.
=> Fix create rollup deployment script

verifyMainnetDeployment/verifyMainnetProofVerifier.md
update document  for elderberry - fork.8
=> update verify document

deployment/testV1ToV2/README.md, deployment/v2/README.md
there is 
> `trustedAggregatorTimeout`: uint64, If a sequence is not verified in this timeout everyone can verify it
so it's confusing if we don't mention that `pendingStateTimeout` means **everyone** can consolidate it after this timeout because for trusted aggregator, it doesn't need to honor this timeout:
```
function consolidatePendingState(
uint32 rollupID,
uint64 pendingStateNum
) external {
RollupData storage rollup = rollupIDToRollupData[rollupID];
// Check if pending state can be consolidated
// If trusted aggregator is the sender, do not check the timeout or the emergency state
if (!hasRole(_TRUSTED_AGGREGATOR_ROLE, msg.sender)) {
if (isEmergencyState) {
revert OnlyNotEmergencyState();
}
if (!_isPendingStateConsolidable(rollup, pendingStateNum)) {
revert …
```
=> avoid confusion in README.md

deployment/v2/verifyContracts.js
update from #219 
I am not very skilled about pr. 😑
=> fix: wrong variable name in verify script 

contracts/mocks/DaiMock.sol
I noticed that it's not possible to build the contracts with `forge` on `linux/arm` because solc `0.5.12` is not available. This patch resolves the problem.
Initial steps:
```bash
$ docker run --rm -it node:20-bookworm /bin/bash
$ curl -L https://foundry.paradigm.xyz | bash && source /root/.bashrc && foundryup
$ git clone https://github.com/0xPolygonHermez/zkevm-contracts.git
$ cd zkevm-contracts
$ npm install
$ printf "[profile.default]\nsrc = 'contracts'\nout = 'out'\nlibs = ['node_modules']\n" > foundry.toml
```
```bash
$ forge build
[⠃] Compiling...2024-03-27T16:26:02.335317Z ERROR foundry_compilers::resolver: failed to resolve versions
[⠊] Compiling...
[⠒] Unable to resolve imports:
"@openzeppelin/contracts-upgradeable/token/ERC20/utils/SafeERC20Upgradeable.sol" in …
```
=> fix: `forge build` on `linux/arm`

contracts/v2/PolygonZkEVMGlobalExitRootV2.sol
The map `l1InfoRootMap` contains for each leaf the corresponding root. So the name is more clear `leafIndex` instead of `depositCount`
```
mapping(uint32 leafIndex => bytes32 l1InfoRoot) public l1InfoRootMap;
```
Also is rename the event `InitL1InfoRootMap`
=> Rename DepositCount leafIndex (Banana)

contracts/v2/PolygonRollupManager.sol, contracts/v2/interfaces/IPolygonRollupManager.sol, contracts/v2/lib/PolygonConsensusBase.sol
- rename `PessimisticChains` to `NonZkChains`
- Fix mocks with new implementations (no changes)
- Fix `rollupManagerNotUpgraded` (no changes)
- do interface `RollupManager`
- review delete contants not used since pendingState and Fees are deleted (no changes)
-`addNewRollupType` --> renaming genesis since it is used in different ways or another param
=> mini updates

contracts/v2/PolygonRollupManager.sol, contracts/v2/consensus/validium/PolygonValidiumEtrog.sol, contracts/v2/interfaces/IPolygonRollupManager.sol, contracts/v2/interfaces/IPolygonZkEVMEtrogErrors.sol, contracts/v2/interfaces/IPolygonZkEVMVEtrogErrors.sol, contracts/v2/lib/PolygonConsensusBase.sol, contracts/v2/lib/PolygonRollupBaseEtrog.sol, contracts/v2/previousVersions/PolygonRollupBaseEtrogPrevious.sol, src/pessimistic-utils.js, test/contractsv2/PolygonPessimisticConsensus.test.ts, test/contractsv2/PolygonRollupManager-Pessimistic.test.ts, test/contractsv2/PolygonRollupManager.test.ts, test/contractsv2/PolygonValidiumEtrog.test.ts, test/contractsv2/PolygonZkEVMEtrog.test.ts
- change PP public from `selectedGER` to `l1InfoTreeRoot`
- select `l1InfoTreeRoot` via `l1InfoTreeLeafCount`
- update test
- only allow `transitionChains` to call `onSequenceBatches` as a safety measure
- add `_disableInitializers();` in consensus implementations for best practices
- update test
- typo `IPolygonZkEVMVEtrogErrors.sol` -->  `IPolygonZkEVMEtrogErrors.sol`
=> selectedGER to l1infotree

contracts/v2/consensus/validium/PolygonValidiumEtrog.sol, contracts/v2/interfaces/IPolygonZkEVMVEtrogErrors.sol, contracts/v2/lib/PolygonRollupBaseEtrog.sol, test/contractsv2/PolygonZkEVMEtrog.test.ts
- fixes message error `L1InfoRootIndexInvalid` --> `L1InfoTreeLeafCountInvalid`
=> fix error message

contracts/v2/consensus/validium/PolygonValidiumEtrog.sol, contracts/v2/lib/PolygonRollupBaseEtrog.sol, test/contractsv2/PolygonRollupManager.test.ts, test/contractsv2/PolygonRollupManagerUpgrade.test.ts, test/contractsv2/PolygonValidiumEtrog.test.ts, test/contractsv2/PolygonZkEVMEtrog.test.ts
- rename `indexL1InfoRoot` to `l1InfoTreeLeafCount`
=> rename indexL1 to leafCount

contracts/v2/PolygonRollupManager.sol, contracts/v2/PolygonZkEVMGlobalExitRootV2.sol
- It contains the following audit remediation from `sigmaPrime` audit
- `RollupDataReturnV2` to be an address instead of `IPolygonRollupBase` 
- remove comparisons to `true` on `PolygonRollupManager.sol`
- set `getInputPessimsiticBytes` in `PolygonRollupManager.sol` as `external`   
- correct typos & natspec
=> audit remediations

.github/workflows/build-docker.yml, .github/workflows/build-push-docker.yml, .github/workflows/compile.yml, .github/workflows/main.yml, .gitignore, contracts/PolygonZkEVMGlobalExitRootL2.sol, contracts/interfaces/IBasePolygonZkEVMGlobalExitRoot.sol, contracts/v2/PolygonZkEVMBridgeV2.sol, contracts/v2/PolygonZkEVMGlobalExitRootV2.sol, contracts/v2/interfaces/IBridgeL2SovereignChains.sol, contracts/v2/sovereignChains/BridgeL2SovereignChain.sol, contracts/v2/sovereignChains/GlobalExitRootManagerL2SovereignChain.sol, deployment/testnet/prepareTestnet.ts, deployment/v2/1_createGenesis.ts, deployment/v2/4_createRollup.ts, deployment/v2/README.md, deployment/v2/create_rollup_parameters.json.example, deployment/v2/deploy_parameters.json.example, deployment/v2/utils/deployment-utils.ts, deployment/v2/utils/updateVanillaGenesis.ts, docker/scripts/v2/create_rollup_parameters_docker.json, docker/scripts/v2/deploy-dockerv2.sh, hardhat.config.ts, package-lock.json, package.json, test/contractsv2/BridgeL2GasTokenMappedSovereignChains.test.ts, test/contractsv2/BridgeL2GasTokensSovereignChains.test.ts, test/contractsv2/BridgeL2SovereignChain.test.ts, upgrade/upgradePessimistic/upgradePessimistic.ts
Create Bridge and GlobalExitRootManager contracts for Sovereign chains + tests.
`BridgeL2SovereignChain.sol` : extends from `PolygonZkEVMBridgeV2` with the features of:
- Set a bridgeManager address
- Functions to remap and undo remap of token addresses by sovereign token addresses
- Overrided mint/burn functions from BridgeV2 to handle that new remapping
`GlobalExitRootManagerL2SovereignChain.sol` : extends from `PolygonZkEVMGlobalExitRootL2` with the features of:
- New function `insertGlobalExitRoot` only callable by coinbase to update the GER of a Sovereign Chain
=> Sovereign bridge implementation

tools/changeDelayTimelock/.gitignore, tools/changeDelayTimelock/README.md, tools/changeDelayTimelock/changeDelayTimelock.ts, tools/changeDelayTimelock/change_delay_timelock.json.example
This PR includes the tool to change the `minDelay` of the `PolygonZkEVMTimelock` contract.
=> add tool to change minDelay timelock

tools/createSovereignGenesis/README.md, tools/createSovereignGenesis/create-genesis-sovereign-params.json.example, tools/createSovereignGenesis/create-sovereign-genesis.ts, tools/createSovereignGenesis/helpers.ts, tools/utils.js
- On the tooling `createSovereignGenesis`
- fix issue when adding balance to an existing account using `preMintAcocunt`
- adds format genesis output (`geth` format supported)
- add git information on the output 
- support multiple `preMintedAccounts`
- add simple mapping on `output` --> `address <--> SC Name`
- add basic L1 ifnormation from `RollupManager`
- polygonBridgeAddress
- polygonZkEVMGlobalExitRootAddress
- polygonRollupManagerAddress
- polygonZkEVMAddress (rollup address)
- polTokenAddress
=> minor improvements genesis sovereign tool

tools/createSovereignGenesis/create-sovereign-genesis.ts
In `createSovereignGenesis` tool:
- add `emergencyBridgePauser` as an input to the SC
- add `emergencyBridgePauser` in the json output
- 2 spaces on json generated for better readability
=> fix create sovereign genesis tool

deployment/v2/4_createRollup.ts
`v10.1.0-rc.1` contracts deployment fails in the case of pessimistic rollup and non-vanilla client (e.g. cdk-erigon).
```bash
#######################
Added new Rollup Type deployed
#######################
Created new PolygonPessimisticConsensus Rollup: 0x414e9E227e4b589aF92200508aF5399576530E4e
TypeError: ambiguous function description (i.e. matches \"initialize(address)\", \"initialize(uint32,address,uint32,address,address,bytes)\") (argument=\"key\", value=\"initialize\", code=INVALID_ARGUMENT, version=6.13.4)
at makeError (/opt/zkevm-contracts/node_modules/ethers/src.ts/utils/errors.ts:687:21)
at assert (/opt/zkevm-contracts/node_modules/ethers/src.ts/utils/errors.ts:715:25)
at assertArgument (/opt/zkevm-contracts/node_modules/ethers/src.ts/utils/errors.ts:727:5)
at …
```
=> fix: bridge initialize

contracts/v2/AggLayerGateway.sol, contracts/v2/interfaces/IAggLayerGateway.sol, test/contractsv2/AggLayerGateway.test.ts, tools/aggLayerGatewayTools/unsetDefaultAggchainVKey/README.md, tools/aggLayerGatewayTools/unsetDefaultAggchainVKey/parameters.json.example, tools/aggLayerGatewayTools/unsetDefaultAggchainVKey/unsetDefaultAggchainVKey.ts
- explicitly separates functionalities to update & unset `defaultAggchainVKeys` in two functions in order to emit en specific event for each one and be less error prone
=> separate functionalities

contracts/v2/PolygonZkEVMBridgeV2.sol, contracts/v2/interfaces/IBridgeL2SovereignChains.sol, contracts/v2/interfaces/IProxyAdmin.sol, contracts/v2/sovereignChains/BridgeL2SovereignChain.sol, hardhat.config.ts, test/contractsv2/UpgradeableTokens.test.ts
Some reviewed changes:
- Make InvalidZeroNetworkID a custom error
- Use `IProxyAdmin` for `owner()` static call at `_setProxiedTokensManagerFromProxy` 
- Fix `originTokenAddress` comments
- Add `proxiedTokensManager` checks at sov bridge second initializer (as they are in main initializer)
- Refactor `deployWrappedTokenAndRemap` to support deploying weth + add `isNotMintable` param
- Tests for `deployWrappedTokenAndRemap`
- Replace `IERC20` for `ITokenWrappedBridgeUpgradeable`
=> Protocol review

tools/addRollupType/addRollupType.ts
This pull request makes adjustments to the `tools/addRollupType/addRollupType.ts` script to modify how the `aggLayerGatewayAddress` is handled. Specifically, it removes its initialization and validation in one part of the code and reintroduces its initialization in a different context.
* Removed the initialization and validation of `aggLayerGatewayAddress` from the initial setup section of the `main` function. This ensures the address is not unnecessarily checked at the start.
* Reintroduced the initialization of `aggLayerGatewayAddress` later in the `main` function, specifically within a conditional block, aligning its use with the relevant deployment logic.
=> fetch aggLayerGateway only for aggchains

contracts/v2/PolygonRollupManager.sol
- Update `rollup.lastLocalExitRoot = bytes32(0)` comment
- Update legacy vars name function `rollupIDToRollupDataDeserialized`
- Unify logic check no pending batches
=> Remediations migration

contracts/v2/PolygonZkEVMBridgeV2.sol, contracts/v2/interfaces/IBridgeL2SovereignChains.sol, contracts/v2/lib/BridgeLib.sol, contracts/v2/lib/DepositContractBase.sol, contracts/v2/sovereignChains/BridgeL2SovereignChain.sol, hardhat.config.ts, test/contractsv2/BridgeL2SovereignChain.test.ts
Fixed following informationals from https://github.com/agglayer/internal-audit/issues/184
- fix comment in IBridgeL2SovereignChains:InvalidLBTLeaf error
- keep permit comments present in PolygonZkEVMBridgeV2V1010.sol:_permit:1185 & PolygonZkEVMBridgeV2V1010.sol:_permit:1243
- in BridgeLib:returnDataToString is an internal function. It should be renamed as the _returnDataToString
- in DepositContractBase:_isValidSubtreeFrontier ensure that not matched siblings are zero (just to not set random values to the new frontier)
- in BridgeL2SovereignChain.sol --> events BackwardLET & ForwardLET add also the previousDepositCount& previusRoot
- in BridgeL2SovereignChain.sol:763 --> it is not the GER, is the LER. Rename to avoid confiusion.
- in BridgeL2SovereignChain.sol:779 --> it is not a …
=> Fix found informationals
